### ISSUE TITLE
Questions about Evaluation(Table 4.) and Implementation.

### ISSUE THREAD

**Issue by minimini-1** [LeapLabTHU/ImprovedNAT#2]
Hello,  
Thank you for your impressive work. I am also interested in image generation based on vector quantization, and I think the approach of optimizing only p(r), r, τ₁, τ₂, and s is highly efficient.

I have one question regarding the evaluation setup about text to image generation on MS-COCO.
Could you please clarify if the AutoNAT-S model trained on ImageNet was combined with a BERT encoder and then optimized with alternating optimization on the COCO train dataset? Thank you!

**Comment by nzl-thu** [comment]
Hi, thank you for your interest in our work!

The AutoNAT-S model on both ImageNet and MS-COCO employs a BERT encoder. The primary difference lies in the text-to-image generation task, where the condition embedding length is longer for the MS-COCO dataset due to the use of text embeddings as conditioning inputs. Other processes remain consistent with those used for the ImageNet dataset.

**Comment by minimini-1** [comment]
Thanks for your reply!
